name: Checks

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - run: |
        pip install -r requirements.txt
        cp config/example_config.json_copy config/develop.json

    - run: |
        python manage.py check
