name: Checks

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-lastet

    steps:
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: >-
          ssh ${DEPLOY_USER}@${DEPLOY_HOST} -t "ls -al"
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
