name: Checks

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/cache@v1
        with:
          path: ./pyenv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Prepare dependencies
        run: |
          python -m venv ./pyenv
          source pyenv/bin/activate
          pip install -r requirements.txt
          cp config/example_config.json_copy config/develop.json

      - name: Run tests
        run: |
          source pyenv/bin/activate
          python manage.py check

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: >-
          ssh-keyscan ${DEPLOY_HOST} >> ~/.ssh/known_hosts
          ssh ${DEPLOY_USER}@${DEPLOY_HOST} -A "ls -al"
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_MESSAGE: 'Nueva version de https://hacktivistas.com/ esta en linea! :rocket:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
